{"cells":[{"cell_type":"markdown","metadata":{"tags":["headers"],"id":"fr9RmY8NOUHh"},"source":["<center><a target=\"_blank\" href=\"https://academy.constructor.org/\"><img src=https://lh3.googleusercontent.com/d/1EmH3Jks5CpJy0zK3JbkvJZkeqWtVcxhB width=\"800\" style=\"background:none; border:none; box-shadow:none;\" /></a> </center>\n","\n","_____\n","<center> <h1>  </h1> </center>\n","<center> <h1> Live coding 3: Error Handling And Exceptions </h1> </center>\n","\n","<p style=\"margin-bottom:1cm;\"></p>\n","\n","_____\n","\n","<center>Constructor Academy, 2025</center>"]},{"cell_type":"markdown","metadata":{"tags":["headers"],"id":"yTMMHBpuOUHk"},"source":["<div style=\"background:#EEEDF5;border-top:0.1cm solid #EF475B;border-bottom:0.1cm solid #EF475B;\">\n","    <div style=\"margin-left: 0.5cm;margin-top: 0.5cm;margin-bottom: 0.5cm;color:#303030\">\n","        <p><strong>Goal:</strong> learn about the try/except method and how to catch errors</p>\n","        <strong> Outline:</strong>\n","        <a id='P0' name=\"P0\"></a>\n","        <ol>\n","            <li> <a style=\"color:#303030\" href='#I'>Introduction </a> </li>\n","            <li> <a style=\"color:#303030\" href='#P1'>Exception Errors</a></li>\n","            <li> <a style=\"color:#303030\" href='#P2'>Handling the Exceptions</a></li>\n","            <li> <a style=\"color:#303030\" href='#P3'>Example - Preventing Crashes with Wrong User Inputs</a></li>\n","            <li> <a style=\"color:#303030\" href='#CL'>Further Reading (Optional)</a></li>\n","        </ol>\n","        <strong>Topics Trained:</strong> Error Handling, Exception, Python\n","    </div>\n","</div>\n","\n","<nav style=\"text-align:right\"><strong>\n","        <a style=\"color:#00BAE5\" href=\"https://constructor.app/learn/courses/f45190af-1e40-4fb3-b0f4-b062878d55a9/view/content/5ff0f127-9f6c-481d-91fb-27af0a765669\" title=\"momentum\"> Module 1, The Data Science Toolkit </a>|\n","        <a style=\"color:#00BAE5\" href=\"https://constructor.app/learn/courses/f45190af-1e40-4fb3-b0f4-b062878d55a9/view/content/5ff0f127-9f6c-481d-91fb-27af0a765669/b5c79da5-6bce-4ad0-b750-630d45769526\" title=\"momentum\">Day 1, Python Fundamentals </a>|\n","        <a style=\"color:#00BAE5\" href=\"https://drive.google.com/uc?export=download&id=1fTISeFrMWkx_yWxWjrd_GeTJaOMxq06E\" title=\"momentum\"> Live Coding 3, Error Handling And Exceptions</a>\n","</strong></nav>"]},{"cell_type":"markdown","metadata":{"id":"Rqud5gWhOUHk"},"source":["<a id='I' name=\"I\"></a>\n","## [Introduction](#P0)"]},{"cell_type":"markdown","metadata":{"id":"mtaJmfACOUHk"},"source":["Exceptions are special objects which are used to manage errors that arise during the execution of programs. Usually, exceptions will crash your program. However, Python gives you a convenient way to handle such errors through so-called exception handling. Exception handling helps you catch errors, and provide a way to deal with them so that your program doesn't crash. When you think that you have a code that could produce an error you should use exception handling.\n","Whenever we do something wrong, Python creates an exception object. If an unhandled exception occurs, your program will stop running and Python will show a stacktrace or traceback which includes the exact location where the error occurred and which error occurred.\n","\n","Exceptions can be handled with try-except blocks:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"id":"wgFBfd_TOUHl","executionInfo":{"status":"error","timestamp":1709887374158,"user_tz":-60,"elapsed":276,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"8cc7f960-cede-432e-e33f-e449da6b243c"},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-65966e0a195f>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m10\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["print(10 / 0)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"wh6HSWv7OUHm","executionInfo":{"status":"ok","timestamp":1709887380540,"user_tz":-60,"elapsed":275,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"ed3c10a3-fe5f-4a27-e07b-4335be564713"},"outputs":[{"output_type":"stream","name":"stdout","text":["Can't divide by zero\n"]}],"source":["try:\n","    print(10 / 0)\n","except ZeroDivisionError:\n","    print(\"Can't divide by zero\")"]},{"cell_type":"markdown","metadata":{"id":"zFrKqUnGOUHm"},"source":["The try block tells Python to try a block of code. If that block of code runs successfully then the except block is skipped. If the try block is unsuccessful Python jumps to the except block, which tells Python what to do. When you use try-except blocks, your programs will continue running even if things start to go wrong. Instead of tracebacks, which can be confusing for users to read, you will see a friendly error message that you have written. If the error is not too serious, you can avoid crashing your program using try-except blocks."]},{"cell_type":"markdown","metadata":{"id":"oSAg_Ia6OUHm"},"source":["<a id='P1'></a>\n","## [Exception Errors](#P0)"]},{"cell_type":"markdown","metadata":{"id":"QORJoRIeOUHn"},"source":["- `IOError`: if the file cannot be opened\n","- `ImportError`: if the code cannot import a module\n","- `ValueError`: when the argument has the right type but an inappropriate value\n","- `KeyboardInterrupt`: raised when the user hits the interrupt key (normally ctrl-C)\n","- `EOFError`: when the input() reads no data, hits an end-of-file condition (EOF)\n","- `ZeroDivisionError`: when you try to divide by zero\n","\n","and [many, many more](https://docs.python.org/3/library/exceptions.html#built-in-exceptions)"]},{"cell_type":"markdown","metadata":{"id":"NNQuEmMCOUHn"},"source":["<a id='P2'></a>\n","## [Handling the Exceptions](#P0)"]},{"cell_type":"markdown","metadata":{"id":"hSdbRd23OUHn"},"source":["We know it's impossible to divide by zero, if we ask Python to do that it will raise an error."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":297},"id":"rwoekTCkOUHn","executionInfo":{"status":"error","timestamp":1709887383994,"user_tz":-60,"elapsed":357,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"5429b219-7175-40f9-b502-0b483f9ee798"},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-791dbb7e08f7>\u001b[0m in \u001b[0;36m<cell line: 6>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mnormalize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;31m# (.5, .5)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0mnormalize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-5-791dbb7e08f7>\u001b[0m in \u001b[0;36mnormalize\u001b[0;34m(a, b)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mnormalize\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0msum\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0ma\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0mb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mnormalize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;31m# (.5, .5)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["def normalize (a, b):\n","    sum = a+b\n","    return (a/sum, b/sum)\n","\n","normalize(1,1) # (.5, .5)\n","normalize(0,0)"]},{"cell_type":"markdown","metadata":{"id":"LCLeQpGsOUHn"},"source":["When this happens, Python stops the program and tells us what kind of exception has been raised. It also shows us where it happened in the form of a stack trace.\n","\n","However, would it not be better to handle this error gracefully? We can use exception handling to modify our program, to tell Python what to do when this kind of exception occurs. That way, if it happens again, weâ€™re prepared."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3j9yzedsOUHn","executionInfo":{"status":"ok","timestamp":1709887385377,"user_tz":-60,"elapsed":3,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"fa77a2bf-0919-4d46-83ee-69323166577e"},"outputs":[{"output_type":"execute_result","data":{"text/plain":["(0, 0)"]},"metadata":{},"execution_count":6}],"source":["def normalize (a, b):\n","    try:\n","        sum = a+b\n","        return (a/sum, b/sum)\n","    except ZeroDivisionError:\n","        return (0, 0)\n","\n","normalize(1,1) # (.5, .5)\n","normalize(0,0) # (0, 0)"]},{"cell_type":"markdown","metadata":{"id":"H5atbct5OUHo"},"source":["Ok, so far so good! But what if we want to do the following:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":263},"id":"VHAy9rQLOUHo","executionInfo":{"status":"error","timestamp":1709887387192,"user_tz":-60,"elapsed":378,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"f62ca6c4-34df-43a6-cfaf-e69a7f6d62b8"},"outputs":[{"output_type":"error","ename":"TypeError","evalue":"unsupported operand type(s) for +: 'int' and 'str'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-65d1dd2a5b2d>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mnormalize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"1\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-6-3505c243e556>\u001b[0m in \u001b[0;36mnormalize\u001b[0;34m(a, b)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mnormalize\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0msum\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0ma\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0mb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}],"source":["normalize(1, \"1\")"]},{"cell_type":"markdown","metadata":{"id":"bhEeZzpMOUHo"},"source":["It looks like adding a string and a number might not be such a good idea. That also means that except only catches the error you defined. You can handle this by using chained except clauses:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"WIX85s_XOUHo"},"outputs":[],"source":["def normalize (a, b):\n","    try:\n","        sum = a+b\n","        return (a/sum, b/sum)\n","    except ZeroDivisionError:\n","        return (0, 0)\n","    except TypeError:\n","        print(\"Wrong types\")\n","        return (-1, -1)\n","    except:\n","        print(\"Another error has occurred\")"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"VbDMpyfmOUHo","executionInfo":{"status":"ok","timestamp":1709887390544,"user_tz":-60,"elapsed":2,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"036e1733-6cf3-4208-8782-74706af52194"},"outputs":[{"output_type":"execute_result","data":{"text/plain":["(0.5, 0.5)"]},"metadata":{},"execution_count":9}],"source":["normalize(1,1)   # (.5, .5)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ktnROBCWOUHo","executionInfo":{"status":"ok","timestamp":1709887390829,"user_tz":-60,"elapsed":2,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"777bfeb3-14aa-4682-a00e-55e86d94128f"},"outputs":[{"output_type":"execute_result","data":{"text/plain":["(0, 0)"]},"metadata":{},"execution_count":10}],"source":["normalize(0,0)   # (0, 0)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"RMAHitncOUHo","executionInfo":{"status":"ok","timestamp":1709887391918,"user_tz":-60,"elapsed":2,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"843bc385-8ad8-4477-a03a-a57dd64dc440"},"outputs":[{"output_type":"stream","name":"stdout","text":["Wrong types\n"]},{"output_type":"execute_result","data":{"text/plain":["(-1, -1)"]},"metadata":{},"execution_count":11}],"source":["normalize(\"a\",0) # (0, 0)"]},{"cell_type":"markdown","metadata":{"id":"N1n4pXLfOUHo"},"source":["The try-except statement works as follows:\n","\n","- Attempt to execute the try clause\n","- If no exception occurs, we are done - skip all except clauses\n","- If exception occurs, go through all defined except handlers from top to bottom\n","    * If the exception's type matches, execute the except clause. If the exception handler does not raise another exception, we're done\n","    * if exception occurs but does not match the type, skip the except clause.\n","\n","There is the special except without the name of the exception. This will catch any exception, and you should avoid it as much as possible."]},{"cell_type":"markdown","metadata":{"id":"3_HUkKHAOUHp"},"source":["<a id='P3'></a>\n","## [Example - Preventing Crashes with Wrong User Inputs](#P0)"]},{"cell_type":"markdown","metadata":{"id":"-jDuEtXHOUHp"},"source":["If we ask the users to give a number as an integer to our program and the user provide a letter instead we have to catch that error and let the user know that the program only accepts numbers:\n","For example:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":297},"id":"EidHWNT8OUHp","executionInfo":{"status":"error","timestamp":1709887420584,"user_tz":-60,"elapsed":21819,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"d64c37cd-d725-4376-d91c-94a4e5ac494e"},"outputs":[{"name":"stdout","output_type":"stream","text":["Write a number: 90\n","90\n","Write a number: 1\n","1\n","Write a number: 2\n","2\n","Write a number: exit\n"]},{"output_type":"error","ename":"ValueError","evalue":"invalid literal for int() with base 10: 'exit'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-13-71c252aff24d>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mwhile\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0musers_input\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Write a number: \"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0musers_input\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'exit'"]}],"source":["while 1:\n","    users_input = int(input(\"Write a number: \"))\n","    print(users_input)"]},{"cell_type":"markdown","metadata":{"id":"CELoNCr7OUHp"},"source":["To fix this we have to add a try/except and and provide the ValueError as an exception:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"74mAVsvdOUHp","executionInfo":{"status":"ok","timestamp":1709887432341,"user_tz":-60,"elapsed":7361,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"d2fb2243-2701-472f-9fc9-5f9acbd0b602"},"outputs":[{"output_type":"stream","name":"stdout","text":["Write a number: 1\n","1\n"]}],"source":["while 1:\n","    try:\n","        users_input = int(input(\"Write a number: \"))\n","        print(users_input)\n","    except ValueError:\n","        print(\"Please use only numbers\")\n","    else:\n","        break"]},{"cell_type":"markdown","metadata":{"id":"_aDoui3IOUHp"},"source":["Let's assume we have the simple app that divides two numbers and we have to handle ZeroDivisionError and show the result. That will look something like this:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"2xCCS9JsOUHp","executionInfo":{"status":"ok","timestamp":1709887466595,"user_tz":-60,"elapsed":22381,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"03c0568c-6401-4e7d-99ad-630e4b1dcdee"},"outputs":[{"output_type":"stream","name":"stdout","text":["First number: 90\n","Second number: 0\n","No zeros please\n","First number: two\n","Please use only numbers\n","First number: 2\n","Second number: 90\n","0.022222222222222223\n"]}],"source":["while 1:\n","    try:\n","        first_number = int(input(\"First number: \"))\n","        second_number = int(input(\"Second number: \"))\n","        answer = first_number / second_number\n","    except ValueError:\n","        print(\"Please use only numbers\")\n","    except ZeroDivisionError:\n","        print(\"No zeros please\")\n","    else:\n","        # we got the correct input - print answer, and exit the while 1 loop\n","        print(answer)\n","        break"]},{"cell_type":"markdown","metadata":{"id":"mKyAfoqiOUHp"},"source":["Any code that depends on the try block succeeding is added to the else block. In this case if the division operation is successful, we use the else block to print the result."]},{"cell_type":"markdown","metadata":{"id":"8XnJ415LOUHp"},"source":["<a id='CL'></a>\n","## [Further Reading (Optional)](#P0)"]},{"cell_type":"markdown","metadata":{"id":"XVCnNrjvOUHp"},"source":["### Example - FileNotFoundError exception"]},{"cell_type":"markdown","metadata":{"id":"0AOHXdiROUHp"},"source":["One common issue when working with files is handling missing files. The file youâ€™re looking for might be in a different location, the filename may be misspelled, or the file may not exist at all. You can handle all of these situations in a straightforward way with a try-except block."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":176},"id":"LCxmIHIfOUHp","executionInfo":{"status":"error","timestamp":1709887475598,"user_tz":-60,"elapsed":236,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"40be67ba-c0f1-487f-dbba-2f554bd73819"},"outputs":[{"output_type":"error","ename":"FileNotFoundError","evalue":"[Errno 2] No such file or directory: 'constructor_students.txt'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-16-c488d92a8ac7>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mfilename\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"constructor_students.txt\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mfile\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilename\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;31m# -> FileNotFoundError: [Errno 2] No such file or directory: 'constructor_students.exe'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'constructor_students.txt'"]}],"source":["filename = \"constructor_students.txt\"\n","file = open(filename)\n","# -> FileNotFoundError: [Errno 2] No such file or directory: 'constructor_students.exe'"]},{"cell_type":"markdown","metadata":{"id":"iaLppg9ROUHq"},"source":["To fix this we can use the FileNotFoundError exception."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"lXz1a5iZOUHq","executionInfo":{"status":"ok","timestamp":1709887478068,"user_tz":-60,"elapsed":2,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"b63f4d38-8ddc-40dc-f838-bf34768666bd"},"outputs":[{"output_type":"stream","name":"stdout","text":["This file <constructor_students.txt> was not found\n"]}],"source":["filename = \"constructor_students.txt\"\n","try:\n","    file = open(filename)\n","except FileNotFoundError:\n","    print(\"This file <{}> was not found\".format(filename))\n","    file = open(\"defaults.txt\", 'w')"]},{"cell_type":"markdown","metadata":{"id":"Lkd7perxOUHq"},"source":["Sometime we don't want to report every exception we catch. Sometimes we want our program to 'fail' silently when an exception occurs and continue on like nothing has happened. In this case we can use the pass statement."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"gd3QyCtlOUHq"},"outputs":[],"source":["filename = \"constructor_students.txt\"\n","try:\n","    open(filename)\n","except FileNotFoundError:\n","    pass"]},{"cell_type":"markdown","metadata":{"id":"oV3HTGZdOUHq"},"source":["Now when a FileNotFoundError is raised, the code in the except block runs, but nothing happens. No traceback is produced, and thereâ€™s no output in response to the error that was raised."]},{"cell_type":"markdown","metadata":{"id":"xXr3TnLhOUHt"},"source":["### Custom Exceptions\n","\n","Let's create some custom exceptions by creating a light version of number guess game from the exercises we had."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"zgKm7fcNOUHt","executionInfo":{"status":"ok","timestamp":1709887513232,"user_tz":-60,"elapsed":18508,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"d3fe0bd3-a3cc-4033-d0a5-49be5987973e"},"outputs":[{"output_type":"stream","name":"stdout","text":["Enter a number: 1\n","This value is too small, try again!\n","Enter a number: 5\n","This value is too small, try again!\n","Enter a number: 8\n","This value is too small, try again!\n","Enter a number: 20\n","This value is too large, try again!\n","Enter a number: 15\n","This value is too large, try again!\n","Enter a number: 12\n","This value is too large, try again!\n","Enter a number: 10\n","Congratulations! You guessed it correctly.\n"]}],"source":["# define Python user-defined exceptions\n","class Error(Exception):\n","    \"\"\"Base class for other exceptions\"\"\"\n","    pass\n","\n","class ValueTooSmallError(Error):\n","    \"\"\"Raised when the input value is too small\"\"\"\n","    pass\n","\n","class ValueTooLargeError(Error):\n","    \"\"\"Raised when the input value is too large\"\"\"\n","    pass\n","\n","# our main program\n","# user guesses a number until he/she gets it right\n","\n","# you need to guess this number\n","number = 10\n","\n","while True:\n","    try:\n","        i_num = int(input(\"Enter a number: \"))\n","        if i_num < number:\n","            raise ValueTooSmallError\n","        elif i_num > number:\n","            raise ValueTooLargeError\n","        break\n","    except ValueTooSmallError:\n","        print(\"This value is too small, try again!\")\n","    except ValueTooLargeError:\n","        print(\"This value is too large, try again!\")\n","\n","print(\"Congratulations! You guessed it correctly.\")"]},{"cell_type":"markdown","metadata":{"id":"DLbfo1huOUHt"},"source":["### Finally\n","The finally clause:"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"GramAdsqOUHu","executionInfo":{"status":"ok","timestamp":1709887519801,"user_tz":-60,"elapsed":234,"user":{"displayName":"Adriano Persegani","userId":"17739764701888244413"}},"outputId":"9b089ec9-e93c-470c-c413-ba4382224694"},"outputs":[{"output_type":"stream","name":"stdout","text":["Uh uh! Value is too large!\n","Bye\n"]}],"source":["try:\n","    raise ValueTooLargeError\n","except ValueTooLargeError:\n","    print(\"Uh uh! Value is too large!\")\n","finally:\n","    print('Bye')"]},{"cell_type":"markdown","metadata":{"id":"a9I8RQNWOUHu"},"source":["Finally always gets executed before leaving the try statement. Unhandled exceptions are re-raised after finally executes."]},{"cell_type":"markdown","metadata":{"id":"E89lmbG6OUHu"},"source":["<div style=\"border-top:0.1cm solid #EF475B\"></div>\n","    <strong><a href='#Q0'><div style=\"text-align: right\"> <h3>End of this Notebook.</h3></div></a></strong>"]}],"metadata":{"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.9"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}